import pandas as pd
import matplotlib.pyplot as plt

datas = pd.read_csv("./whites.csv", sep=";")

plt.scatter(datas["quality"], datas["fixed acidity"])
# plt.hist(datas["fixed acidity"])
plt.ylabel("fixed acidity")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/fixed_acidity.png")
plt.clf()

plt.scatter(datas["quality"], datas["volatile acidity"])
# plt.hist(datas["volatile acidity"])
plt.ylabel("volatile acidity")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/volatile_acidity.png")
plt.clf()

plt.scatter(datas["quality"], datas["citric acid"])
# plt.hist(datas["citric acid"])
plt.ylabel("citric acid")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/citric_acid.png")
plt.clf()

plt.scatter(datas["quality"], datas["residual sugar"])
# plt.hist(datas["residual sugar"])
plt.ylabel("residual sugar")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/residual_sugar.png")
plt.clf()

plt.scatter(datas["quality"], datas["chlorides"])
# plt.hist(datas["chlorides"])
plt.ylabel("chlorides")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/chlorides.png")
plt.clf()

plt.scatter(datas["quality"], datas["free sulfur dioxide"])
# plt.hist(datas["free sulfur dioxide"])
plt.ylabel("free sulfur dioxide")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/free_sulfur_dioxide.png")
plt.clf()

plt.scatter(datas["quality"], datas["total sulfur dioxide"])
# plt.hist(datas["total sulfur dioxide"])
plt.ylabel("total sulfur dioxide")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/total_sulfur_dioxide.png")
plt.clf()

plt.scatter(datas["quality"], datas["density"])
# plt.hist(datas["density"])
plt.ylabel("density")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/density.png")
plt.clf()

plt.scatter(datas["quality"], datas["pH"])
# plt.hist(datas["pH"])
plt.ylabel("pH")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/pH.png")
plt.clf()

plt.scatter(datas["quality"], datas["sulphates"])
# plt.hist(datas["sulphates"])
plt.ylabel("sulphates")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/sulphates.png")
plt.clf()

plt.scatter(datas["quality"], datas["alcohol"])
# plt.hist(datas["alcohol"])
plt.ylabel("alcohol")
plt.xlabel("Quality")
plt.legend()
plt.savefig("./images/histo/alcohol.png")
plt.clf()
